name: Build on Windows 10 with .NET 10 Preview

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 10 Preview
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.100-preview.4'
      - name: Restore dependencies
        run: dotnet restore --framework net10.0-windows
      - name: Build
        run: dotnet build --framework net10.0-windows --configuration Release --no-restore
      - name: Test
        run: echo "No tests defined for this project."
